name: CI
on:
  workflow_dispatch:

jobs:     
  build-site:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@v2
    - name: Install Claat CLI
      run: |
        sudo apt install golang-go
        sudo env GOPATH=/root/go
        sudo go get github.com/googlecodelabs/tools/claat
        sudo cp /root/go/bin/claat /usr/bin/
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install python libraries
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert
    - name: Fetch and convert from notion
      run: |
        wget -O ./_markdowns/raw/data.zip ${{ secrets.NOTION_RECOSTEP }} 
        python convert.py
        rm ./_markdowns/raw/data.zip
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Convert to codelabs
      run: |
        cp -r ./_notebooks/img ./site/codelabs 2>/dev/null || :
        for file in ./_notebooks/*.ipynb
        do
          jupyter nbconvert --output-dir="./site/codelabs" --to markdown "$file"
        done
        cp -r ./_markdowns/img/* ./site/codelabs/img 2>/dev/null || :
        cp -r ./_markdowns/*.md ./site/codelabs 2>/dev/null || :
        cd ./site/codelabs/
        for file in ./*.md
        do
          claat export "$file"
        done
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install npm
      run: |
        cd ./site/
        npm install
        npm install -g npm
        npm install -g gulp-cli
    - name: Build Site
      run: |
        cd ./site/
        gulp dist
        rm -rf ./stage
        mkdir ./stage
        cp -r ./dist/ ./stage
        rm ./stage/dist/codelabs
        cp -r ./codelabs ./stage/dist
    - name: Add CNAME
      run: |
        cd ./site/stage/dist
        touch CNAME
        echo 'step.recohut.com' > CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/stage/dist
        publish_branch: gh-pages
